### ISSUE TITLE
Filtering /entries endpoint

### ISSUE THREAD

**Issue by MichaelT372** [dmdigital/timeneye-api#7]
Hi there,

How do I filter the /entries endpoint?

If I want to do a limit and I try https://track.timeneye.com/api/3/entries?limt=50 and I don't get any responses and I believe a POST request to /entries is for making a new entry.

The regular /entries endpoint is working fine for me. I'm using PHP & cURL.

**Comment by Bouhtouch** [comment]
Hi Michael,
just add a slash "/" before the question mark and it should work.

**Comment by MichaelT372** [comment]
ahh thank you! Tested via Postman and it works.
