### ISSUE TITLE
Get clients with Entries API

### ISSUE THREAD

**Issue by slobadx** [dmdigital/timeneye-api#8]
GET /Entries returns all related data about each entry except the reported client by user.

**Comment by Bouhtouch** [comment]
Hi @slobadx, 
thank you for your feedback.

Yes it will be available once we release the update of our APIs, we don't have an ETA at the moment but we will release an announcement on our blog and our developers mailing-list once it's out.

Kind regards,
Anas B.

**Comment by slobadx** [comment]
Hi, do you have news about when the release with related clients in entries will be added? 
This is a very important factor.
